src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EmployeeSkill__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Time__c</fullName>
        <label>Assigned Time</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Skills</relationshipLabel>
        <relationshipName>EmployeeSkills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Team Lead</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Project Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Employee Skills r</relationshipLabel>
        <relationshipName>EmployeeSkills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EmployeeSkill</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>EmployeeSkills Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EmployeeSkills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/L_ProjectDetailsController.cls
public with sharing class L_ProjectDetailsController {
    // @AuraEnabled
    // /* Return all objs 'Words__c' where Subject__c == subject */
    // public static List<EmployeeSkill__c> getEmployeeSkillsByProjectID(String ID) {
    //     EmployeeSkill__c[]  employeeSkillList = new EmployeeSkill__c[]{};
        
    //     try {
    //         for (EmployeeSkill__c[] employeeSkillListBatch : [
    //                 SELECT ID,
    //                     Employee__r.First_Name__c,
    //                     Employee__r.Last_Name__c,
    //                     Assigned_Time__c,
    //                     Position__c,
    //                     Project__c
    //                 FROM EmployeeSkill__c
    //                 WHERE Project__c = :ID
    //             ]) {

    //             employeeSkillList.addAll(employeeSkillListBatch);
    //         }
    //     }
    //     catch (QueryException e) {
    //         System.debug(e.getMessage());
    //         System.debug(e.getTypeName());
    //         System.debug(e.getLineNumber());
    //     }
    //     catch (Exception e) {
    //         System.debug(e.getMessage());
    //         System.debug(e.getTypeName());
    //         System.debug(e.getLineNumber());
    //     }

    //     return employeeSkillList;
    // }

    @AuraEnabled
    /* Return all objs 'Words__c' where Subject__c == subject */
    public static List<EmployeeSkillWrapper> getEmployeeSkillsByProjectID(String ID) {
        EmployeeSkill__c[]  employeeSkillList = new EmployeeSkill__c[]{};
        
        try {
            for (EmployeeSkill__c[] employeeSkillListBatch : [
                    SELECT ID,
                        Employee__r.First_Name__c,
                        Employee__r.Last_Name__c,
                        Employee__r.Availability__c,
                        Assigned_Time__c,
                        Position__c,
                        Project__c
                    FROM EmployeeSkill__c
                    WHERE Project__c = :ID
                ]) {

                employeeSkillList.addAll(employeeSkillListBatch);
            }
        }
        catch (QueryException e) {
            System.debug(e.getMessage());
            System.debug(e.getTypeName());
            System.debug(e.getLineNumber());
        }
        catch (Exception e) {
            System.debug(e.getMessage());
            System.debug(e.getTypeName());
            System.debug(e.getLineNumber());
        }

        // Map<ID, EmployeeSkill__c> employeeSkillMap = new Map<ID, EmployeeSkill__c>(employeeSkillList);
        ID[] employeeIDs = new ID[]{};

        for (EmployeeSkill__c employeeSkill : employeeSkillList) {
            employeeIDs.add(employeeSkill.Employee__c);
        }

        AggregateResult[] sumEmployeeAssignedTimeList = [
            SELECT Employee__r.ID, SUM(Assigned_Time__c) sum
            FROM EmployeeSkill__c
            WHERE Employee__c = :employeeIDs
            GROUP BY Employee__r.ID
        ];

        // System.debug(sumEmployeeAssignedTimeList);

        Map<ID,Integer> employeeIDAndSumAssignedTimeMap = new Map<ID,Integer>();

        for (AggregateResult result : sumEmployeeAssignedTimeList) {
            employeeIDAndSumAssignedTimeMap.put((ID)result.get('Id'), Math.round((Decimal)result.get('sum')));
        }

        EmployeeSkillWrapper[] employeeSkillWrapperList = new EmployeeSkillWrapper[]{};

        for (EmployeeSkill__c employeeSkill : employeeSkillList) {
            Integer employeeAvailability = Math.round((Decimal)employeeSkill.Employee__r.Availability__c);
            Integer employeeSumAssignedTime = employeeIDAndSumAssignedTimeMap.get(employeeSkill.Employee__c);

            Integer freeHours = employeeAvailability - employeeSumAssignedTime;

            EmployeeSkillWrapper employeeSkillWrapper = new EmployeeSkillWrapper();
            employeeSkillWrapper.ID = employeeSkill.ID;
            employeeSkillWrapper.employeeID = employeeSkill.Employee__c;
            employeeSkillWrapper.projectID = employeeSkill.Project__c;
            employeeSkillWrapper.position = employeeSkill.Position__c;
            employeeSkillWrapper.assignedTime = Math.round((Decimal)employeeSkill.Assigned_Time__c);
            employeeSkillWrapper.employeeAvailability = Math.round((Decimal)employeeSkill.Employee__r.Availability__c);
            employeeSkillWrapper.employeeFreeHours = freeHours;
            employeeSkillWrapper.employeeSumAssignedTime = employeeSumAssignedTime;
            employeeSkillWrapper.employeeFirstName = employeeSkill.Employee__r.First_Name__c;
            employeeSkillWrapper.employeeLastName = employeeSkill.Employee__r.Last_Name__c;

            employeeSkillWrapperList.add(employeeSkillWrapper);
        }

        System.debug(employeeSkillWrapperList);

        return employeeSkillWrapperList;
    }

    @AuraEnabled
    /* Return all values from picklist */
    public static List<String> getPicklistValuesFromObject(String objectName, String fieldName) {
        return L_SchemaService.getPicklistValues(objectName, fieldName);
    }

    /* Return all values from picklist */
    private static List<String> getSSS(String objectName, String fieldName) {
        return L_SchemaService.getPicklistValues(objectName, fieldName);
    }

    public class EmployeeSkillWrapper {
        @AuraEnabled
        public ID ID {get; set;}
        @AuraEnabled
        public ID employeeID {get; set;}
        @AuraEnabled
        public ID projectID {get; set;}
        @AuraEnabled
        public String position {get; set;}
        @AuraEnabled
        public Integer assignedTime {get; set;}
        @AuraEnabled
        public Integer employeeAvailability {get; set;}
        @AuraEnabled
        public Integer employeeFreeHours {get; set;}
        @AuraEnabled
        public Integer employeeSumAssignedTime {get; set;}
        @AuraEnabled
        public String employeeFirstName {get; set;}
        @AuraEnabled
        public String employeeLastName {get; set;}
    }
}